### ROOT SERVER
GET http://localhost:4000/

### MAIL ENDPOINT
GET http://localhost:4000/mail/


### PROJECT ENDPOINTS 
GET http://localhost:4000/projects/


### PROJECT ENDPOINTS POST // ADD A PROJECT TO DB 
POST http://localhost:4000/projects/
Content-Type: application/json

{
    "title":"DAD JOKES",
    "subtitle":"Front end project using React",
    "description":"You're a funny guy, but you keep losing your list of jokes and forgetting which ones had the best reactions! Well worry no more- Dad (or bad??) jokes app to the rescue.",
    "website":"https://dadjokes-seven.now.sh/",
    "github":"https://github.com/ch04937/dadjokes"
}
### PROJECT ENDPOINTS DEL // REMOVE A PROJECT FROM DB 
DELETE http://localhost:4000/projects/3
Content-Type: application/json

{
    "id":3
}